/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchievementPopup: typeof import('./src/components/achievement/AchievementPopup.vue')['default']
    AppHeader: typeof import('./src/components/base/AppHeader.vue')['default']
    AppTabBar: typeof import('./src/components/base/AppTabBar.vue')['default']
    BossBubble: typeof import('./src/components/npc/BossBubble.vue')['default']
    CartBar: typeof import('./src/components/cart/CartBar.vue')['default']
    ComplianceBanner: typeof import('./src/components/base/ComplianceBanner.vue')['default']
    DishList: typeof import('./src/components/dish/DishList.vue')['default']
    NpcStatus: typeof import('./src/components/npc/NpcStatus.vue')['default']
    OnboardingGuide: typeof import('./src/components/base/OnboardingGuide.vue')['default']
    ReviewCard: typeof import('./src/components/review/ReviewCard.vue')['default']
    ReviewModal: typeof import('./src/components/review/ReviewModal.vue')['default']
    RiderBubble: typeof import('./src/components/npc/RiderBubble.vue')['default']
    RiderMap: typeof import('./src/components/order/RiderMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopCard: typeof import('./src/components/shop/ShopCard.vue')['default']
    ShopHeader: typeof import('./src/components/shop/ShopHeader.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
